// Usamabhanbhro homepage: original campaign language and visual system expressed through an image-led editorial commerce journey.
import { Link } from "wouter";
import { collections, featuredProducts, journals, newArrivalProducts } from "@/lib/catalog";
import { useCommerce } from "@/lib/commerce";
import { ProductCard } from "@/components/ProductCard";

const heroImage = "/manus-storage/usamabhanbhro-editorial-hero-higgsfield_a2a808c4.webp";
const campaignImage = "/manus-storage/usamabhanbhro-editorial-hero-higgsfield_a2a808c4.webp";
export default function Home() { useCommerce(); return <>
  <section className="hero hero--home"><img className="hero__image" src={heroImage} alt="A warm editorial study of considered leather and home objects" /><div className="hero__veil" /><div className="hero__content"><p className="eyebrow eyebrow--light">Object study 01</p><h1>THE BEAUTY<br />OF USE.</h1><p>Made slowly. Carried often.</p><Link className="text-link" href="/collections/new-arrivals">Explore the new edit <span>↗</span></Link></div><span className="hero__scroll">Scroll to explore ↓</span></section>
  <section className="story-links" aria-label="Featured edits"><Link className="story-link story-link--wide" href="/collections/new-arrivals"><span>THE NEW EDIT</span><strong>Objects for the way you move.</strong><span className="story-link__cta">Shop new arrivals</span></Link><Link className="story-link" href="/collections/signature"><span>SIGNATURE FORMS</span><strong>Quietly expressive.</strong><span className="story-link__cta">Discover signature</span></Link><Link className="story-link" href="/collections/bags"><span>BAGS</span><strong>Carry considered.</strong><span className="story-link__cta">Shop bags</span></Link></section>
  <section className="product-section"><div className="section-heading"><div><p className="eyebrow">Selected pieces</p><h2>New objects, considered.</h2></div><Link className="text-link" href="/collections/new-arrivals">View new arrivals <span>↗</span></Link></div><div className="product-rail">{newArrivalProducts().slice(0, 4).map((product) => <ProductCard key={product.id} product={product} />)}</div></section>
  <section className="product-section product-section--signature"><div className="section-heading"><div><p className="eyebrow">The house edit</p><h2>Objects that stay close.</h2></div><Link className="text-link" href="/collections/signature">Explore signature <span>↗</span></Link></div><div className="product-rail">{featuredProducts().slice(0, 4).map((product) => <ProductCard key={product.id} product={product} />)}</div></section>
  <section className="editorial-wrap"><div className="campaign-motion"><div className="campaign-motion__image"><img src={campaignImage} alt="Original tactile studio composition of folded leather and textile" /><span className="campaign-motion__play">▶</span></div><div className="campaign-motion__copy"><p className="eyebrow eyebrow--light">A studio in motion</p><h2>The beauty<br />of use.</h2><p>Discover the thinking, making, and material choices behind the pieces.</p><Link className="text-link" href="/journal/the-shape-of-a-day">Read the journal <span>↗</span></Link></div></div>
    <div className="editorial-grid">{journals.map((journal, index) => <Link className={`editorial-card editorial-card--${index + 1}`} href={`/journal/${journal.slug}`} key={journal.slug}><div className="editorial-card__image"><img src={journal.image} alt={journal.title} loading="lazy" /></div><div className="editorial-card__copy"><p className="eyebrow">{journal.type}</p><h3>{journal.title}</h3><p>{journal.excerpt}</p><span className="text-link">Read more <span>↗</span></span></div></Link>)}</div>
  </section>
  <section className="home-collections"><div className="section-heading"><div><p className="eyebrow">A considered wardrobe</p><h2>Find your material.</h2></div><Link className="text-link" href="/collections">All collections <span>↗</span></Link></div><div className="collection-strip">{collections.slice(0, 3).map((collection) => <Link className="collection-tile" href={`/collections/${collection.slug}`} key={collection.slug}><img src={collection.image} alt={collection.name} loading="lazy" /><span>{collection.name}</span></Link>)}</div></section>
  <section className="home-demo-note"><p className="eyebrow">A client-ready commerce concept</p><h2>Designed to become<br />something real.</h2><p>Every product, cart, wishlist, and payment state in this showcase is local and demonstrative. The architecture is ready for a future secure commerce service.</p><Link className="text-link" href="/about">Read the studio note <span>↗</span></Link></section>
 </>; }
